spring:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: false

provider:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule